_wandb:
    value:
        cli_version: 0.21.0
        e:
            299dv8yqv1tcyufv0v65kfn0qw0byhkv:
                codePath: test.ipynb
                codePathLocal: test.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1081101176832"
                        used: "48544092160"
                email: v.butkov@graph-it.co.uk
                executable: /home/rataski/HappyAI-subnet/.venv/bin/python
                git:
                    commit: 11454318b35e3bc5ee25c002f6f19a5775437760
                    remote: https://github.com/graph-it-uk/HappyAI-subnet.git
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-804745e1-bfca-45f9-a6cf-0177391df60c
                host: DESKTOP-19N3ADV
                memory:
                    total: "16671514624"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/rataski/HappyAI-subnet/test.ipynb
                python: CPython 3.12.3
                root: /home/rataski/HappyAI-subnet
                startedAt: "2025-07-16T19:34:41.338627Z"
                writerId: 299dv8yqv1tcyufv0v65kfn0qw0byhkv
        m: []
        python_version: 3.12.3
        t:
            "3":
                - 2
                - 13
                - 67
                - 69
            "4": 3.12.3
            "5": 0.21.0
            "8":
                - 1
            "12": 0.21.0
            "13": linux-x86_64
